//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nganhtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diemsinhvien
    {
        public int id { get; set; }
        public string masinhvien { get; set; }
        public string monhoc { get; set; }
        public Nullable<double> dieml1 { get; set; }
        public Nullable<double> dieml2 { get; set; }
        public Nullable<double> dieml3 { get; set; }
        public Nullable<double> dieml4 { get; set; }
        public string kq { get; set; }
    
        public virtual Sinhvien Sinhvien { get; set; }
    }
}
