//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nganhtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giaovien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giaovien()
        {
            this.Tailieux = new HashSet<Tailieu>();
        }
    
        public string magiaovien { get; set; }
        public string manganh { get; set; }
        public string tengiaovien { get; set; }
        public string pass { get; set; }
    
        public virtual Nganh Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tailieu> Tailieux { get; set; }
    }
}
