//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nganhtinhoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NTHEntities : DbContext
    {
        public NTHEntities()
            : base("name=NTHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diemsinhvien> Diemsinhviens { get; set; }
        public virtual DbSet<Giaovien> Giaoviens { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<Sinhvien> Sinhviens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taikhoan> Taikhoans { get; set; }
        public virtual DbSet<Tailieu> Tailieux { get; set; }
        public virtual DbSet<Thoikhoabieu> Thoikhoabieux { get; set; }
        public virtual DbSet<Thongbao> Thongbaos { get; set; }
        public virtual DbSet<Thongbaotruong> Thongbaotruongs { get; set; }
        public virtual DbSet<Tuyendung> Tuyendungs { get; set; }
    }
}
