//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nganhtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tailieu
    {
        public int id { get; set; }
        public string tentailieu { get; set; }
        public string text { get; set; }
        public string file { get; set; }
        public string magiaovien { get; set; }
    
        public virtual Giaovien Giaovien { get; set; }
    }
}
